server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: book_route
          uri: http://localhost:8080
          predicates:
            - Path=/books/**
          filters:
            - PrefixPath=/api/v1

management:
  endpoints:
    web:
      exposure:
        include: "*"
