server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: book_route
          uri: http://book-service
          predicates:
            - Path=/books/**
          filters:
            - PrefixPath=/api/v1
        - id: order_route
          uri: http://order-service
          predicates:
            - Path=/orders/**
          filters:
            - PrefixPath=/api/v1
        - id: user_route
          uri: http://user-service
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/api/v3
        - id: cart_route
          uri: http://${CART_PUBLIC_ENDPOINT}
          predicates:
            - Path=/cart/**
          filters:
            - PrefixPath=/api/v1
